#============= 测试环境 =====================

#端口号
server:
  port: 80
####数据源DataSource1#####
spring:
  datasource:
    url: jdbc:mysql://192.168.0.88:3306/GJB_zkd?useUnicode=true&amp;characterEncoding=utf-8;zeroDateTimeBehavior=convertToNull
    username: root
    password: guanjiapo
    driver-class-name: com.mysql.jdbc.Driver